#!/bin/sh

set -x

mkdir build
cd build
cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm@5/ -DCMAKE_INSTALL_PREFIX=$(pwd) -DZIG_LIBC_INCLUDE_DIR=/usr/include
make VERBOSE=1
make install

./zig build --build-file ../build.zig test --verbose
